### ISSUE TITLE
Организовать работу с GitHub

### ISSUE THREAD

**Issue by hypnospinner** [Light1984/3Dplatformer#1]
### Базовые термины

**commit** - единица локального изменения.
**push/pull** - отправление/загрузка данных на удаленный репозиторий (*remote repository*)

### Ветки

**branches** - различные "параллельные" версии проекта, созданные для реализации отдельных фич и прочих задач

Ветки могут быть разбиты по разным принципам:
- по задачам/фичам (<- я за такое разбиение)
- по разработчикам

**Pull request** - запросы на слияние веток. master - основная ветка, в которой хранится главная рабочая версия проекта. Все серьезные новые изменения вносятся в ветки, а затем они сливаются с мастером.

Там ты можешь попросить кого-то из contributors сделать review - прокомментировать созданный запрос и принять или не принять его, попросив внести те или иные изменения

**Как я предлагаю называть ветки?**

Название должно точно и ясно отражать, что ты планируешь реализовать в ветке. Например: если ты хочешь сделать систему движения, есть смысл назвать ветку: feature/movement-system

### Issues

По сути **issue** - трэд для обсуждения той или иной тем - исправления бага, добавления новой фичи.

У issue есть ряд настроек:

- *Assignees*
     Здесь перечислены contributors, которых "связали" с этим issue (это может подразумевать реализацию фичи или исправления бага)

- *Labels*
    Это тэги. Мы не хотим тэгами относить issues к тем или иным областям проектирования, мы хотим показать отношение к issues: urgent (срочно), important (важно), groundwork (черновая работа) и т.д.

- *Projects*
    Проекты - метод организации проектирования т.е. задач приложения. Например мы хотим иметь противников в игре. Это объемная инженерная задача, для которой можно создать проект и связывать все issues, относящиеся к этому проекту.

    Issues: научить AI использовать укрытия
    Project: Enemies and AI

- *Milestone*
   Это попытка организовать работу во времени. Например можно сделать milestone "Prototype"

### Wiki

Здесь описываются любые технические, организационные и прочие детали проекта. Фактически это своего рода документация.

## Что нужно сделать?

- [x] Определится с ТЗ

- [x] Определить Labels

- [x] Определить Projects

- [x] Определить Milestone

- [x] Создать нужные ветки

- [x] Добавить Readme

- [x] Добавить Description

- [x] Добавить лицензию (GNU)

**Comment by hypnospinner** [comment]
@Light1984 
Добавил [уточнённое ТЗ к прототипу](
https://github.com/Light1984/3Dplatformer/wiki/%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5-%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5#%D0%A3%D0%BE%D1%87%D0%BD%D1%91%D0%BD%D0%BD%D0%BE%D0%B5-%D0%A2%D0%97-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%B5%D1%80%D0%B2%D0%BE%D0%B3%D0%BE-%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D1%82%D0%B8%D0%BF%D0%B0). Прошу до 16 декабря написать отзыв и правки

**Comment by hypnospinner** [comment]
@Light1984 
> Открытая область - некая промежуточная локация с нпс и всякими тайничками
> ЗАкрытая область - просто линейный уровень

Я подразумевал их как некоторые уровни внутри открытого мира по ходу прохождения которых игрок открывает срезы по которым легче вернуться к месту где он проиграл (или по ходу которых находятся редкие и не очень чек-поинты) и то, и то - полноправные уровни, просто один подвязан на квест - другой просто показать, что ты делаешь что-то, чтобы открыть что-то

> Также из врагов можно добавить простых, парящих в воздухе
> И также можно придумать хотя бы одного босса

Парящие в воздухе? чем они опасны? они как-то преcледуют игрока? или просто висят около точки?

Я не думаю, что босс - хорошая идея, это достаточно сложно и может потребовать слишком много времени для прототипа. Как доп. задача пойдет, но ИМХО не вижу в нем пока смысла.

>К собираемым способностям персонажа можно добавить хождение по воде, отскок по стенам, бесконечное кручение(атака), двойной прыжок и супер атака

Не думаю, что нужно ТАК много способностей. Нам нужно показать механику, показать идею, а не реализовать ее на 50%. Нам нужно 5% идеи.

**Comment by Light1984** [comment]
> @hipnospinner
В открытой области тоже будут некие выполняемые квесты, но весь главный геймплей будет в закрытых уровнях (пример Sonic the Hedgehog 2006)
При прохождении уровней тебе открываются некие двери к другим уровням или целым локациям.


Парящие в воздухе могут принципе чем-то стрелять, но они могут послужить как некие платформы (С помощью комбинации ударов пролететь по врагам и преодолеть пропасть, над которой они висели)

Ну тогда из способностей оставить на прототип двойной прыжок и супер атаку

**Comment by hypnospinner** [comment]
### Об уровнях

Моя идея заключалась в том, что сделать своего рода платформер в открытом мире, где игрок ограничен лишь своими возможностями. Мы можем остановиться на идее с уровнями-дверьми.

Я так понимаю, ты проходишь уровень, оказываешься на хаб-локации и открывается новый, ты идёшь в него, переходишь на локацию уровня и проходишь его.

На чем останавливаемся?

Кстати, думаю, что даже супер атака будет лишней для прототипа

**Comment by Light1984** [comment]
Просто кажется, что в случае открытого мира сюжет будет сложно сделать в платформе, в основном это побегушки.
По сути правильно понял, только хаб локация не будет как в Crash Bandicoot, что ты просто так открываешь ячейку с новым уровнем и наступаешь на нее чтоб начать его. Сама хаб локация будет полна интересных сайде квестов, тайных интересных уголков (тип как в Гарри Поттере носишься и собираешь всякие коллекционные карточки и открываешь много классных локаций)

Принципе можно пока и отказаться от этой способности
Думаю, что способности будут выглядеть в виде неких аксессуаров или деталей одежды персонажа(Ну так, на заметку)

**Comment by hypnospinner** [comment]
Отлично! Тогда я создаю все организационное для работы и с завтрашнего дня начинаем девать!
