### ISSUE TITLE
Разработать систему передвижения персонажа

### ISSUE THREAD

**Issue by Light1984** [Light1984/3Dplatformer#2]
### Базовые возможности перемещения

- [x] Ходьба и Бег 
Персонаж начинает с ходьбы и начинает разгонятся до определенной скорости
- [x] Прыжок и двойной прыжок
Мы даем ему еще раз прыгнуть в воздухе, но в 2 раза короче первого
- [x] Проверка касания поверхности
Создать коллайдер, который будет считывать касание с поверхностью

**Comment by hypnospinner** [comment]
> ### Базовые возможности перемещения
> * [ ]  Ходьба и Бег
>   Персонаж начинает с ходьбы и начинает разгонятся до определенной скорости

То есть нет никакой кнопки разделяющей бег и ходьбу?
Я так понял, что персонаж разгоняется, чтобы достичь максимальной скорости, а не делает это моментально

*мне кажется лучше сделать через нажатие на клавишу, но тоже через ускорение*

> * [ ]  Прыжок и двойной прыжок
>   Мы даем ему еще раз прыгнуть в воздухе, но в 2 раза короче первого

Возможно было бы неплохо, если игрок мог поменять направление движения во время прыжка именно за счет второго. Т.е. управляемость в полете у игрок должна быть почти нулевой, но за счет такого вот трюка, можно моментально ее поменять и лететь уже в бок или назад.

> * [ ]  Проверка касания поверхности
>   Создать коллайдер, который будет считывать касание с поверхностью

Ref: [OnCollisionStay](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnCollisionStay.html)

**Comment by hypnospinner** [comment]
Двойной прыжок отнесен к сменяемым способностям

**Comment by hypnospinner** [comment]
### Закрытие issue

Было решено использовать для прототипа упрощенную версию movement system CharacterController

For details see Pull Request #20
